#pragma once

#include <core/sloth_defines.h>
#include <core/sloth_list.h>

using namespace sloth;

namespace dust {

    enum InventoryItemType {
        INVENTORY_ITEM_TYPE_NONE = 0,

        INVENTORY_ITEM_TYPE_RAW_MATERIAL_BEGIN,
        INVENTORY_ITEM_TYPE_ORE_IRON,
        INVENTORY_ITEM_TYPE_ORE_COPPER,
        INVENTORY_ITEM_TYPE_ORE_SULPHUR,
        INVENTORY_ITEM_TYPE_ORE_ALUMINUM,
        INVENTORY_ITEM_TYPE_ORE_CRUDE_OIL,
        INVENTORY_ITEM_TYPE_ORE_WATER,
        INVENTORY_ITEM_TYPE_ORE_SILICON,
        INVENTORY_ITEM_TYPE_RAW_MATERIAL_END,

        // Refinery
        INVENTORY_ITEM_TYPE_STEEL_INGOT,
        INVENTORY_ITEM_TYPE_COPPER_WIRE,
        INVENTORY_ITEM_TYPE_ALUMINUM_PLATE,
        INVENTORY_ITEM_TYPE_PETROL,
        INVENTORY_ITEM_TYPE_LUBRICANT,
        INVENTORY_ITEM_TYPE_GLASS,

        // Chemical Plant
        INVENTORY_ITEM_TYPE_SULPHURIC_ACID,
        INVENTORY_ITEM_TYPE_GUNPOWDER,
        INVENTORY_ITEM_TYPE_RUBBER,
        INVENTORY_ITEM_TYPE_PLASTIC,
        INVENTORY_ITEM_TYPE_SILICON_WAFER,
        INVENTORY_ITEM_TYPE_PURIFIED_WATER,

        // Vechicle Chassis
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_BEGIN,
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_BUGGY,
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_TRUCK,
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_APC,
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_TANK,
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_CRAWLER,
        INVENTORY_ITEM_TYPE_VEHICLE_CHASSIS_END,

        // Vechicle Armour Parts
        INVENTORY_ITEM_TYPE_ARMOUR_BEGIN,
        INVENTORY_ITEM_TYPE_ARMOUR_WOOD_PLANKS,
        INVENTORY_ITEM_TYPE_ARMOUR_STEEL_PLATING,
        INVENTORY_ITEM_TYPE_ARMOUR_END,

        // Vechicle Power Parts
        INVENTORY_ITEM_TYPE_POWER_BEGIN,
        INVENTORY_ITEM_TYPE_POWER_FUEL_TANK,
        INVENTORY_ITEM_TYPE_POWER_BATTERY,
        INVENTORY_ITEM_TYPE_POWER_END,

        // Vechicle Engine Parts
        INVENTORY_ITEM_TYPE_ENGINE_BEGIN,
        INVENTORY_ITEM_TYPE_ENGINE_PETROL,
        INVENTORY_ITEM_TYPE_ENGINE_ELECTRIC,
        INVENTORY_ITEM_TYPE_ENGINE_END,

        // Vechicle Tire Parts
        INVENTORY_ITEM_TYPE_TIRE_BEGIN,
        INVENTORY_ITEM_TYPE_TIRE_SHRUB,
        INVENTORY_ITEM_TYPE_TIRE_RUBBER,
        INVENTORY_ITEM_TYPE_TIRE_END,

        INVENTORY_ITEM_TYPE_TURRET_BEGIN,
        INVENTORY_ITEM_TYPE_TURRET_MINING_LASER,
        INVENTORY_ITEM_TYPE_TURRET_BULLET_GUN,
        INVENTORY_ITEM_TYPE_TURRET_END,
    };

    struct InventoryItem {
        InventoryItemType type;
        i32 amount;
        i32 flatIndex;
    };

    constexpr u32 INVENTORY_CAPACITY = 64;

    struct Inventory {
        i32 xSize;
        i32 ySize;
        FixedList<InventoryItem, INVENTORY_CAPACITY> items;
    };

}